#include "storage/rowset/unique_rowset_id_generator.h"

#include "util/spinlock.h"
#include "util/starrocks_metrics.h"
#include "util/uid_util.h"

namespace starrocks {

UniqueRowsetIdGenerator::UniqueRowsetIdGenerator(const UniqueId& backend_uid) : _backend_uid(backend_uid), _inc_id(0) {
    REGISTER_GAUGE_STARROCKS_METRIC(rowset_count_generated_and_in_use, [this]() {
        std::lock_guard<SpinLock> l(_lock);
        return _valid_rowset_id_hi.size();
    });
}

// generate a unique rowset id and save it in a set to check whether it is valid in the future
RowsetId UniqueRowsetIdGenerator::next_id() {
    RowsetId rowset_id;
    rowset_id.init(_version, ++_inc_id, _backend_uid.hi, _backend_uid.lo);
    {
        std::lock_guard<SpinLock> l(_lock);
        _valid_rowset_id_hi.insert(rowset_id.hi);
    }
    return rowset_id;
}

bool UniqueRowsetIdGenerator::id_in_use(const RowsetId& rowset_id) const {
    // if rowset_id == 1, then it is an old version rowsetid, not gc it
    // because old version rowset id is not generated by this code, so that not delete them
    if (rowset_id.version < _version) {
        return true;
    }
    if ((rowset_id.mi != _backend_uid.hi) || (rowset_id.lo != _backend_uid.lo)) {
        return false;
    }

    std::lock_guard<SpinLock> l(_lock);
    return _valid_rowset_id_hi.count(rowset_id.hi) == 1;
}

void UniqueRowsetIdGenerator::release_id(const RowsetId& rowset_id) {
    if (rowset_id.version < _version) {
        return;
    }
    if ((rowset_id.mi != _backend_uid.hi) || (rowset_id.lo != _backend_uid.lo)) {
        return;
    }
    std::lock_guard<SpinLock> l(_lock);
    _valid_rowset_id_hi.erase(rowset_id.hi);
}

} // namespace starrocks
